apiVersion: v1
kind: Service
metadata:
  name: deis-database
  namespace: deis
  labels:
    heritage: deis
spec:
  ports:
  - name: http
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    name: deis-database
