# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160114_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='app',
        ),
        migrations.RemoveField(
            model_name='container',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='container',
            name='release',
        ),
        migrations.DeleteModel(
            name='Container',
        ),
    ]
