# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 20:18
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160607_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='healthcheck',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
