# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 21:59
from __future__ import unicode_literals

import api.models.key
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_config_healthcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='routable',
            field=models.BooleanField(default=True),
        ),
    ]
