# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 16:03
from __future__ import unicode_literals

import api.models.key
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_config_healthcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id'], 'permissions': (('use_app', 'Can use app'),), 'verbose_name': 'Application'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['name', 'common_name', 'expires']},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['domain', 'certificate']},
        ),
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ['public'], 'verbose_name': 'SSH Key'},
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.TextField(error_messages={'unique': 'Domain is already in use by another application'}, unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='public',
            field=models.TextField(error_messages={'unique': 'Public Key is already in use'}, unique=True, validators=[api.models.key.validate_base64]),
        ),
    ]
