# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160816_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='push',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='push',
            name='app',
        ),
        migrations.RemoveField(
            model_name='push',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Push',
        ),
    ]
