# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160816_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='whitelist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
