# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 17:32
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160830_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='autoscale',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
