# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 17:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_appsettings_autoscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='whitelist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=None, size=None),
        ),
    ]
