# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160930_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
