# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 16:11
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_release_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='label',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
