# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:19
from __future__ import unicode_literals

import api.models.certificate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_appsettings_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='key',
            field=models.TextField(validators=[api.models.certificate.validate_private_key]),
        ),
    ]
