# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_private_key_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='deploy_now',
            field=models.BooleanField(default=True),
        ),
    ]
