# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_field_deploy_now_to_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
    ]
