# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 14:37
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_app_k8s_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='sidecarfile',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
