# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 18:42
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_app_k8s_name_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='lifecycle_post_start',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AddField(
            model_name='config',
            name='lifecycle_pre_stop',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
